Presentation
------------
Smoggle is a cross-platform C++ software for emulating tablatures on internal speaker and distributed under LGPL license. It requires the [libxml](http://www.xmlsoft.org/) library for loading and saving tablatures in XML format. An example of tablature using this file format is given below:

<?xml version="1.0" encoding="UTF-8"?>
<score tempo="150" name="My music score">
  <block loops="2">
    <block>
      <note value="C,4" />
      <note value="D,4" />
      <note value="E,4" />
      <note value="F,4" />
      <note value="G,4" />
      <note value="A,4" />
      <note value="B,4" />
    </block>
    <pause duration="3.0" />
    <block>
      <note value="B,5" />
      <note value="A,5" />
      <note value="G,5" />
      <note value="F,5" />
      <note value="E,5" />
      <note value="D,5" />
      <note value="C,5" />
    </block>
    <pause duration="3.0" />
  </block>
</score>

The tag names are chosen to be relatively short, intuitive and memorable for unexperienced users but also to ease their sharing. Only this file format is currently supported but conversion to or from other file formats remains not difficult.

Compiling
---------
Go into the root directory and just type `make` in a terminal. 

Running
-------
The software can be run by typing the following command in a terminal:

./main -f TABLATURE_FILENAME

where TABLATURE_FILENAME denotes the filename of the tablature (several examples are provided in the "data" directory"). Please add the `--help' flag to get more information about available options.

Documentation
-------------
The LaTeX / HTML documentation in the "doc" directory can be generated by typing `make doc` in a terminal.
